### ISSUE TITLE
Add Search to docs

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/lisk-docs#15]
### Description
Add a search bar for internal docs search.

### Additional information
https://docusaurus.io/docs/search

**Comment by Tschakki** [comment]
We probably need to wait to apply for DocSearch, until the website is published, see the [checklist](https://docsearch.algolia.com/docs/who-can-apply/)

**Comment by Tschakki** [comment]
> We probably need to wait to apply for DocSearch, until the website is published, see the [checklist](https://docsearch.algolia.com/docs/who-can-apply/)

The website is now publicly available 🎉  https://documentation.lisk.com/

**Comment by TalhaMaliktz** [comment]
I have applied for DocSearch! Will update once, I receive the relevant code from them.
