### ISSUE TITLE
Add Sepolia LSK Faucet URL

### ISSUE THREAD

**Issue by TalhaMaliktz** [LiskHQ/lisk-docs#156]
### Description

Add Sepolia LSK Faucet URL to Sepolia network info

- https://app.optimism.io/faucet (grants sepETH)
- https://sepolia-faucet.lisk.com/ (grants LSK)

### Location

`network-info`

**Comment by shuse2** [comment]
We shouldn't update the faucet URL. it should be addition.
Optimism faucet gives ETH, the lisk one only gives LSK
