### ISSUE TITLE
Update source documentation to cater for libsodium compilation

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-docs#17]
With the release of `0.5.1` and the switch to `libsodium` we need to update our source install documentation. Compilation is automated but requires some extra dependencies to make it happen.

**Comment by Isabello** [comment]
Are you sure? npm install takes care of this in the install documentation since we install sodium as part of that process.  Or are there external OS package dependencies?

**Comment by karmacoma** [comment]
```
sudo apt-get update
sudo apt-get install -y autoconf automake build-essential curl git libtool python
```

We are missing `autoconf`, `automake`, `libtool`.

**Comment by Isabello** [comment]
Ok makes sense that my machine already has thpse.. i will fix
