### ISSUE TITLE
Endpoint not found: Get signature, Register username, Send message.

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-docs#4]
From: https://github.com/LiskHQ/lisk/issues/97

> These endpoints are present in the documentation, but aren't present on the current version of the platform (0.2.1). 

> **Get signature**
> Get second signature of account.
> GET /api/signatures/get?id=id

> **Register username**
> Register username.
> PUT /api/accounts/username

> **Send message**
> Send message to recipient.
> PUT /api/messages

> **API Reference:**
> https://lisk.io/documentation?i=lisk-docs/APIReference

Courtesy of: @vrlc92

**Comment by vrlc92** [comment]
Thanks!

I identified other endpoints:

Removing
Will return dapps that in uninstalling right now.
GET /api/dapps/removing

Icon dapp
Using to get icon of dapp from sia.
GET /api/dapps/icon

**Comment by karmacoma** [comment]
Issue closed in the relevant lisk-docs repository: https://github.com/LiskHQ/lisk-docs/issues/4.

Thanks @vrlc92 👍
