### ISSUE TITLE
Add explanation regarding native yielding integration

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-docs#60]
### Description

Explain how to integrate native yielding tokens as fee token using account abstraction SDK.

### Motivation

We want to users to use the Lido / Diva / etc tokens seamlessly for the fee in Lisk network.
In order to achieve that wallets and applications need to be able to implement the integration easily.

### Dependency
* Main account abstraction direction and SDK needs to be determined

**Comment by TalhaMaliktz** [comment]
**Dependency:** Integration with thirdweb
