### ISSUE TITLE
Add network info for Lisk Mainnet

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/lisk-docs#89]
### Description

Add the network information for the Lisk Mainnet on the following pages:

- [ ] https://documentation.lisk.com/network-info
- [ ] https://documentation.lisk.com/contracts

- [ ] https://documentation.lisk.com/connecting-to-a-wallet
- [ ] https://documentation.lisk.com/add-token-to-lisk

- [ ] https://documentation.lisk.com/building-on-lisk/deploying-a-smart-contract
- [ ] https://documentation.lisk.com/building-on-lisk/interacting-with-the-blockchain

- [ ] https://documentation.lisk.com/lisk-tools/bridges
- [ ] https://documentation.lisk.com/lisk-tools/api-providers

### Additional Information

**Comment by TalhaMaliktz** [comment]
**Dependency:** Mainnet Launch
